// Single source of truth for ADMIN pass trust, read by both the relay
// (server/classroom.mjs) and the browser (src/account/adminKeys.ts re-exports).
//
// TRUSTED_ADMIN_PUBLIC_KEYS: base64url Ed25519 public keys. Several entries are
// allowed so a key can be rotated without invalidating every pass at once.
// REVOKED_PASS_IDS: passIds to refuse even though their signature is valid.
// Both are public data. The PRIVATE key never lives in the repo (see tools/admin/README.md).

export const TRUSTED_ADMIN_PUBLIC_KEYS = [
  // 2026-10-10 key #1 (generated by tools/admin/admin-keygen.mjs)
  '1SED2_vgpWncWdNRO0--_R376BMPAyGXG9m65dofCoE',
]

export const REVOKED_PASS_IDS = []
