import type { ScenarioConfig } from '@/types'

// Downtown San Francisco area — Golden Gate Park vicinity
export const demoBasic: ScenarioConfig = {
  id: 'demo_basic',
  name: 'Demo — Basic Waypoint',
  description: 'Three drones fly a square route. Good for verifying movement and telemetry.',
  seed: 42,
  droneCount: 3,
  missionType: 'waypoint',
  startPosition: { lat: 37.7695, lng: -122.4862 },
  waypoints: [
    { id: 'wp1', position: { lat: 37.7700, lng: -122.4870 }, altitudeFt: 120, label: 'Alpha' },
    { id: 'wp2', position: { lat: 37.7710, lng: -122.4855 }, altitudeFt: 120, label: 'Bravo' },
    { id: 'wp3', position: { lat: 37.7705, lng: -122.4840 }, altitudeFt: 120, label: 'Charlie' },
    { id: 'wp4', position: { lat: 37.7695, lng: -122.4850 }, altitudeFt: 120, label: 'Delta' },
  ],
  // Each drone flies a distinct L-shaped leg of the square
  perDroneWaypoints: {
    'uav-01': [
      { id: 'd1-alpha',   position: { lat: 37.7700, lng: -122.4870 }, altitudeFt: 100, label: 'Alpha' },
      { id: 'd1-bravo',   position: { lat: 37.7710, lng: -122.4855 }, altitudeFt: 100, label: 'Bravo' },
      { id: 'd1-charlie', position: { lat: 37.7705, lng: -122.4840 }, altitudeFt: 100, label: 'Charlie' },
    ],
    'uav-02': [
      { id: 'd2-bravo',   position: { lat: 37.7710, lng: -122.4855 }, altitudeFt: 120, label: 'Bravo' },
      { id: 'd2-charlie', position: { lat: 37.7705, lng: -122.4840 }, altitudeFt: 120, label: 'Charlie' },
      { id: 'd2-delta',   position: { lat: 37.7695, lng: -122.4850 }, altitudeFt: 120, label: 'Delta' },
    ],
    'uav-03': [
      { id: 'd3-charlie', position: { lat: 37.7705, lng: -122.4840 }, altitudeFt: 140, label: 'Charlie' },
      { id: 'd3-delta',   position: { lat: 37.7695, lng: -122.4850 }, altitudeFt: 140, label: 'Delta' },
      { id: 'd3-alpha',   position: { lat: 37.7700, lng: -122.4870 }, altitudeFt: 140, label: 'Alpha' },
    ],
  },
  geofences: [
    {
      id: 'gf1',
      label: 'Restricted Airspace',
      polygon: [
        { lat: 37.7720, lng: -122.4880 },
        { lat: 37.7720, lng: -122.4820 },
        { lat: 37.7730, lng: -122.4820 },
        { lat: 37.7730, lng: -122.4880 },
      ],
      maxAltitudeFt: 0,
      type: 'no_fly',
    },
  ],
  heatSources: [
    { id: 'hs1', class: 'generic-person', position: { lat: 37.7703, lng: -122.4860 }, tempC: 37, radiusM: 3 },
    { id: 'hs2', class: 'vehicle', position: { lat: 37.7708, lng: -122.4848 }, tempC: 85, radiusM: 5 },
  ],
  batteryStartPct: 100,
  batteryDrainRatePerSec: 0.02,
  commsLossWindows: [
    { startSec: 45, durationSec: 8 },
  ],
}

export const demoSAR: ScenarioConfig = {
  id: 'demo_sar',
  name: 'SAR — Parallel Track Grid',
  description: 'Three drones execute a parallel-track search pattern over Golden Gate Park. Thermal detections simulate missing person.',
  seed: 7331,
  droneCount: 3,
  missionType: 'sar_parallel',
  startPosition: { lat: 37.7694, lng: -122.4862 },
  waypoints: [], // generated by SARPlanner at runtime
  searchArea: [
    { lat: 37.7700, lng: -122.4880 },
    { lat: 37.7720, lng: -122.4880 },
    { lat: 37.7720, lng: -122.4840 },
    { lat: 37.7700, lng: -122.4840 },
  ],
  geofences: [
    {
      id: 'gf-sfpd-1',
      label: 'SFO Approach Corridor',
      polygon: [
        { lat: 37.7725, lng: -122.4870 },
        { lat: 37.7730, lng: -122.4870 },
        { lat: 37.7730, lng: -122.4830 },
        { lat: 37.7725, lng: -122.4830 },
      ],
      maxAltitudeFt: 200,
      type: 'restricted',
    },
  ],
  heatSources: [
    { id: 'hs-person-1', class: 'generic-person', position: { lat: 37.7712, lng: -122.4862 }, tempC: 37, radiusM: 2 },
    { id: 'hs-person-2', class: 'generic-person', position: { lat: 37.7707, lng: -122.4848 }, tempC: 37, radiusM: 2 },
    { id: 'hs-vehicle-1', class: 'vehicle', position: { lat: 37.7715, lng: -122.4855 }, tempC: 90, radiusM: 4 },
  ],
  batteryStartPct: 100,
  batteryDrainRatePerSec: 0.015,
  commsLossWindows: [
    { startSec: 60, durationSec: 12 },
  ],
}
