import type { ScenarioConfig } from '@/types'

// Golden Gate Park, San Francisco — a simple, legible area-search demo.
// Three drones each own a parallel lane (~120 m apart N–S) and sweep west→east
// across the same ~350 m box. Lanes never overlap laterally, so the drones are
// separated by real ground distance, not just altitude stacking. Good for
// verifying movement, staggered launch, telemetry, and a clean thermal find.
export const demoBasic: ScenarioConfig = {
  id: 'demo_basic',
  name: 'Demo — Basic Waypoint',
  description: 'Three drones sweep parallel lanes across a search box. Good for verifying coordinated launch, movement, and telemetry.',
  seed: 42,
  droneCount: 3,
  missionType: 'waypoint',
  startPosition: { lat: 37.7701, lng: -122.4862 },
  // Faint backbone = the central lane, drawn for context only.
  waypoints: [
    { id: 'wp1', position: { lat: 37.7701, lng: -122.4882 }, altitudeFt: 120, label: 'Box-W' },
    { id: 'wp2', position: { lat: 37.7701, lng: -122.4842 }, altitudeFt: 120, label: 'Box-E' },
  ],
  // One lane per drone — parallel transects, no shared points, no crossings.
  perDroneWaypoints: {
    'uav-01': [
      { id: 'd1-w', position: { lat: 37.7690, lng: -122.4882 }, altitudeFt: 100, label: 'Lane1-W' },
      { id: 'd1-m', position: { lat: 37.7690, lng: -122.4862 }, altitudeFt: 100, label: 'Lane1-Mid', dwellTimeSec: 10 },
      { id: 'd1-e', position: { lat: 37.7690, lng: -122.4842 }, altitudeFt: 100, label: 'Lane1-E' },
    ],
    'uav-02': [
      { id: 'd2-w', position: { lat: 37.7701, lng: -122.4882 }, altitudeFt: 120, label: 'Lane2-W' },
      { id: 'd2-m', position: { lat: 37.7701, lng: -122.4862 }, altitudeFt: 120, label: 'Lane2-Mid', dwellTimeSec: 10 },
      { id: 'd2-e', position: { lat: 37.7701, lng: -122.4842 }, altitudeFt: 120, label: 'Lane2-E' },
    ],
    'uav-03': [
      { id: 'd3-w', position: { lat: 37.7712, lng: -122.4882 }, altitudeFt: 140, label: 'Lane3-W' },
      { id: 'd3-m', position: { lat: 37.7712, lng: -122.4862 }, altitudeFt: 140, label: 'Lane3-Mid', dwellTimeSec: 10 },
      { id: 'd3-e', position: { lat: 37.7712, lng: -122.4842 }, altitudeFt: 140, label: 'Lane3-E' },
    ],
  },
  geofences: [
    {
      id: 'gf1',
      label: 'Restricted Airspace',
      polygon: [
        { lat: 37.7722, lng: -122.4890 },
        { lat: 37.7722, lng: -122.4834 },
        { lat: 37.7732, lng: -122.4834 },
        { lat: 37.7732, lng: -122.4890 },
      ],
      maxAltitudeFt: 0,
      type: 'no_fly',
    },
  ],
  heatSources: [
    { id: 'hs1', class: 'generic-person', position: { lat: 37.7701, lng: -122.4858 }, tempC: 37, radiusM: 3 },
    { id: 'hs2', class: 'vehicle', position: { lat: 37.7690, lng: -122.4850 }, tempC: 85, radiusM: 5 },
  ],
  batteryStartPct: 100,
  batteryDrainRatePerSec: 0.02,
  commsLossWindows: [
    { startSec: 45, durationSec: 8 },
  ],
}

export const demoSAR: ScenarioConfig = {
  id: 'demo_sar',
  name: 'SAR — Parallel Track Grid',
  description: 'Three drones execute a parallel-track search pattern over Golden Gate Park. Thermal detections simulate missing person.',
  seed: 7331,
  droneCount: 3,
  missionType: 'sar_parallel',
  startPosition: { lat: 37.7694, lng: -122.4862 },
  waypoints: [], // generated by SARPlanner at runtime
  searchArea: [
    { lat: 37.7700, lng: -122.4880 },
    { lat: 37.7720, lng: -122.4880 },
    { lat: 37.7720, lng: -122.4840 },
    { lat: 37.7700, lng: -122.4840 },
  ],
  geofences: [
    {
      id: 'gf-sfpd-1',
      label: 'SFO Approach Corridor',
      polygon: [
        { lat: 37.7725, lng: -122.4870 },
        { lat: 37.7730, lng: -122.4870 },
        { lat: 37.7730, lng: -122.4830 },
        { lat: 37.7725, lng: -122.4830 },
      ],
      maxAltitudeFt: 200,
      type: 'restricted',
    },
  ],
  heatSources: [
    { id: 'hs-person-1', class: 'generic-person', position: { lat: 37.7712, lng: -122.4862 }, tempC: 37, radiusM: 2 },
    { id: 'hs-person-2', class: 'generic-person', position: { lat: 37.7707, lng: -122.4848 }, tempC: 37, radiusM: 2 },
    { id: 'hs-vehicle-1', class: 'vehicle', position: { lat: 37.7715, lng: -122.4855 }, tempC: 90, radiusM: 4 },
  ],
  batteryStartPct: 100,
  batteryDrainRatePerSec: 0.015,
  commsLossWindows: [
    { startSec: 60, durationSec: 12 },
  ],
}
